import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

interface EmailRequest {
  tenantEmail: string;
  tenantName: string;
  landlordName: string;
  pdfUrl: string; // base64 data URL or actual URL
}

export async function POST(req: NextRequest) {
  try {
    const { tenantEmail, tenantName, landlordName, pdfUrl }: EmailRequest = await req.json();

    // Extract PDF data from base64 URL if needed
    let pdfBuffer: Buffer;
    if (pdfUrl.startsWith('data:application/pdf;base64,')) {
      const base64Data = pdfUrl.split(',')[1];
      pdfBuffer = Buffer.from(base64Data, 'base64');
    } else {
      // If it's a regular URL, fetch the PDF
      const response = await fetch(pdfUrl);
      const arrayBuffer = await response.arrayBuffer();
      pdfBuffer = Buffer.from(arrayBuffer);
    }

    // Configure email transporter
    // NOTE: Replace with your actual email service credentials
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: false, // true for 465, false for other ports
      auth: {
        user: process.env.NEXT_EMAIL_USER || 'your-email@gmail.com',
        pass: process.env.NEXT_EMAIL_PASS || 'your-app-password',
      },
    });

    // Email content
    const mailOptions = {
      from: `"${landlordName}" <${process.env.NEXT_EMAIL_USER || 'noreply@leasegenerator.com'}>`,
      to: tenantEmail,
      subject: 'Your Residential Lease Agreement',
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
              }
              .header {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                padding: 30px;
                border-radius: 10px 10px 0 0;
                text-align: center;
              }
              .content {
                background: #f9fafb;
                padding: 30px;
                border-radius: 0 0 10px 10px;
              }
              .button {
                display: inline-block;
                background: #667eea;
                color: white;
                padding: 12px 30px;
                text-decoration: none;
                border-radius: 5px;
                margin: 20px 0;
              }
              .footer {
                text-align: center;
                margin-top: 30px;
                font-size: 12px;
                color: #6b7280;
              }
              .info-box {
                background: white;
                padding: 20px;
                border-radius: 8px;
                margin: 20px 0;
                border-left: 4px solid #667eea;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1 style="margin: 0;">Lease Agreement Ready</h1>
            </div>
            <div class="content">
              <p>Dear ${tenantName},</p>
              
              <p>Your residential lease agreement has been prepared and is attached to this email as a PDF document.</p>
              
              <div class="info-box">
                <h3 style="margin-top: 0;">Next Steps:</h3>
                <ol>
                  <li>Review the attached lease agreement carefully</li>
                  <li>Ensure all terms and conditions are acceptable</li>
                  <li>Sign and date the document</li>
                  <li>Return the signed copy to your landlord</li>
                </ol>
              </div>
              
              <p><strong>Important:</strong> This is a legally binding document. We recommend reviewing it with a legal professional if you have any questions or concerns.</p>
              
              <p>If you have any questions about the lease agreement, please contact ${landlordName} directly.</p>
              
              <div class="footer">
                <p>This email was generated by Lease Generator System</p>
                <p>Generated on ${new Date().toLocaleDateString('en-US', { 
                  weekday: 'long', 
                  year: 'numeric', 
                  month: 'long', 
                  day: 'numeric' 
                })}</p>
              </div>
            </div>
          </body>
        </html>
      `,
      attachments: [
        {
          filename: `Lease_Agreement_${tenantName.replace(/\s+/g, '_')}.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf'
        }
      ]
    };

    // Send email
    const info = await transporter.sendMail(mailOptions);

    console.log('Email sent:', info.messageId);

    return NextResponse.json({ 
      success: true, 
      messageId: info.messageId,
      message: 'Email sent successfully' 
    });

  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to send email' },
      { status: 500 }
    );
  }
}