// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig , env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },

  // schema: "prisma/schema.prisma",
  datasource: {
    // This URL is used for CLI commands (migrations, db push)
    url: env("DIRECT_URL"), 
  },
 
});
